spring:
  security:
    user:
      name: test
      password: test
      
  h2:
    console:
      enabled: true
      
  datasource:
    url: jdbc:h2:mem:mydb
    username: admin
    password: admin
    
server:
  ssl:
    key-store-password: tomcat
    key-store: classpath:mykeystore.p12
    key-store-type: PKCS12
    key-alias: tomcat

  port: 8443